// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proyecto_rutas.App.Persistencia;

namespace proyecto_rutas.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("proyecto_rutas.App.Dominio.Entidades.Acudiente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fijo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("movil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numero_identificacion")
                        .HasColumnType("int");

                    b.Property<string>("primer_apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("segundo_apellido")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Acudientes");
                });

            modelBuilder.Entity("proyecto_rutas.App.Dominio.Entidades.Conductor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("movil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numero_identificacion")
                        .HasColumnType("int");

                    b.Property<string>("primer_apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("segundo_apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tipo_documento")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Conductores");
                });

            modelBuilder.Entity("proyecto_rutas.App.Dominio.Entidades.Estudiante", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("curso")
                        .HasColumnType("int");

                    b.Property<string>("direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("genero")
                        .HasColumnType("int");

                    b.Property<string>("mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("movil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numero_identificacion")
                        .HasColumnType("int");

                    b.Property<string>("primer_apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("segundo_apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tipo_documento")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("proyecto_rutas.App.Dominio.Entidades.Ruta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("cupo_asignado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cupo_disponible")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre_zona")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("zona")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Rutas");
                });

            modelBuilder.Entity("proyecto_rutas.App.Dominio.Entidades.Vehiculo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("capacidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("conductorid")
                        .HasColumnType("int");

                    b.Property<int>("marca")
                        .HasColumnType("int");

                    b.Property<string>("matricula_placa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("rutaid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("conductorid");

                    b.HasIndex("rutaid");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("proyecto_rutas.App.Dominio.Entidades.Vehiculo", b =>
                {
                    b.HasOne("proyecto_rutas.App.Dominio.Entidades.Conductor", "conductor")
                        .WithMany()
                        .HasForeignKey("conductorid");

                    b.HasOne("proyecto_rutas.App.Dominio.Entidades.Ruta", "ruta")
                        .WithMany()
                        .HasForeignKey("rutaid");

                    b.Navigation("conductor");

                    b.Navigation("ruta");
                });
#pragma warning restore 612, 618
        }
    }
}
